### ISSUE TITLE
Track player state via new "ps" key

### ISSUE THREAD

**Issue by wilaw** [cta-wave/common-media-client-data#120]
We should create a key to be able to track different states of playback. Candidate states might be

| Value  | name | Descriptor |
| ------------- | ------------- | ------------- |
| 0  | Startup  | Playback requested and building to target buffer. Content maybe rendering |
| 1 | Steady-state  | Normal playback. Buffers oscillate around their target values |
| 2 | Seeking |  Player moving the playhead to a new position |
| 3 | SwitchingUp | player is raising its bitrate |
| 4 | SwitchingDown | player is reducing the encoded bitrate |
| 5| Paused  | playback is paused |
| 6 | Rebuffering | playback is not rendering and is attmpeting to rebuild buffer |
| 7 | Error | Player has encountered a fatal playback error |

We might be able to repleace the SwitchingUp|Down with a single 'Switching state' and let the 'br' values describe the direction.

**Comment by slhck** [comment]
This is a great suggestion! It would really help if CMCD could be used to derive an accurate representation of what was going on for the user watching the media.

There are some aspects I believe need to be clarified. First, the described states actually happen at two layers:

- Buffer layer (buffering, not buffering, choosing what representation to buffer)
- Presentation layer (stalling, playing, seeking, paused, ended)

The current suggestion is a bit of a mix between those two. The important buffer-level aspects (buffer length and buffer starvation) seem to be already handled by existing keys. With a focus on what the user perceived, I'd prefer transmitting information about the presentation layer.

There's a catch though: the time of sending those states may not correspond to the actual time at which they occurred on the client, because they are bound to the client making a request. This obviously does not apply to the transport mode where an independent JSON request is being sent. But it could lead to the receiving end getting a wrong representation of what actually happened at the client level.

This could be easily mitigated by requiring that, when a state transition is sent, the time of its change is also sent in a separate field (e.g., expressed as an absolute wall clock timestamp, or the *∆(current wall clock time, wall clock time of state change)*, to minimize the request footprint).

I would also suggest renaming/splitting up some states in line with the above considerations.

- **Startup:** maybe this should be separated into “loading” and “playing” states, where the first request made while the player is still waiting to play sends a “loading” state, and only when it has started playing, a “playing” state is sent. This would apply to both initial startup and any stalling happening during the presentation.
- **Steady state**: I am not sure if this is needed at all, when it could be inferred from the buffer length.
- **Seeking:** This is maybe a misnomer; seeking is already completed when this is fired with a new request, so probably “seeked”? We ideally also want know the media timestamp of where the user seeked (although that could be inferred from the request parameters or byte ranges etc.)
- **Switching up/down**: This would be good to have for cases where the `br` value has already changed (because, e.g., the buffer layer loads a higher-resolution content), but the presentation itself is still using the old rendition to avoid quality oscillations. Note that a switch may not be up/down one level, so we must explicitly send the `br` value to which the switch corresponds.
- **Paused:** This would not be possible to transmit unless a player makes a request despite having just been told to pause (which I guess should stop any future requests in steady state). Can only be transmitted once playback resumes.

**Comment by acbegen** [comment]
> 3	SwitchingUp	player is raising its bitrate
> 4	SwitchingDown	player is reducing the encoded bitrate

Are not these actually events and to me, they are not states?

**Comment by slhck** [comment]
Yeah, that's true... actually you could call all these "events" and infer state from them. (They're very similar to the HTML5 media element events.)

**Comment by ZmGorynych** [comment]
Please don't call them events, this will confuse the DASH folks b/c of DASH
events

**Comment by PCaponetti** [comment]
Will: remember these are states, not events. Should be reporting the render position, not buffer position.
Will: for player intent and superseding `msd` we would need timestamps in some modes and it wouldn't be as ergonomic as `msd`.
Piers O: need to expand some state descriptions. Specifically error state.
Rob W: I see rebuffering, startup, and seeking as all very similar.
Paul C: Do we care about interactive interstitials or primary content?

Let's start here on the next meeting.

**Comment by wilaw** [comment]
Paul - should state only be available for state-interval mode.?
Will - we should constrain state to be only SI mode because it is reported 
Alex - it would be useful for response mode. 
Paul - maybe it is useful for responseMode?
Seb - also think it is useful for request and response mode. 
Will - we would need two timestamps if we add state to responseM and requestM
Rob - you could use two modes together.
Will - should use state mode if you want to know about state changes. 
Seb - you could bundle modes in a smart way. 
Paul - you would have to map it together after the fact. 

Now editing state definitions

We took out switch-up/down last time. 
Alex - user-initiated versus application initiated paused. Should we have two states? 
Will - too many states is difficult. Difficult to add for player developers. 
Alex - you can have multiple players , one pauses while the other doesn't. 
Rob - understand problem. May not want to solve with state. Player is backgrounded. My pref is these are player states , relationships between .
Will - add new state called "backgrounded".
Paul - is this same as "not visible"? 
Alex - Roku and native RDK AMD player bother report CMCD. 
Rob - don't like idea of backgorund player state. Could be paused audio state. Advocate for another field - visibility. 
Paul - should add a new key called "backgrounded"? Need a new issue for this. @Paul to add. Also would like to know if user ended playback, versus it ended by itself. 
Will - can we define ended to be "user ended". Actually change my mind. Would be nice to have "abandoned". 


Added some new definitions and a new state

> s - starting: the player has been instructed to play media for a given session
> p - playing : Media is being rendered
> k - seeking : The start of the user initiated action of moving the play position
> r - rebuffering : Media is not being rendered due to insufficient buffer
> a - paused : 
> e - ended
> f - fatal error
> q - quit by user
> This key MUST only be used for state-interval reporting mode.

**Comment by wilaw** [comment]
Nicolas raised the question -  

> Imagine this state: you just loaded a page, and the player already have some buffer. What state would you expect given the description we have? "starting" or "paused"? The player had no instruction to play, so starting sounds is not the correct one, and paused for some reason I expect to be after the player played something.. 

To solve this valid problem, we might consider adding a "preloading" state which indicates that the page has automatically loaded some content. Then when the user initiates playback, we go to starting and then (very quickly) playing.

**Comment by wilaw** [comment]
> To solve this valid problem, we might consider adding a "preloading" state which indicates that the page has automatically loaded some content. 

Added  d - preloading : the player is loading assets ahead of starting in order to provide a fast startup. The expectation is that playback will commence at a future time. 

We also revised the definitions of the states:

> A token describing describing the current playback state of the player as perceived by the end user, one of:
> s - starting: the player has been instructed to play media for a given session, either by a user interaction or by an autoplay action. 
> p - playing : Media is being rendered.
> k - seeking : The start of the user initiated action of moving the playhead position.
> r - rebuffering : Media has stopped being rendered due to an insufficient buffer. This state is not reported during startup or seeking. 
> a - paused : Playback has been intentionally paused.
> e - ended : Rendering has ended due to completion of the media asset playback.
> f - fatal error : Rendering has ended due to an irrecoverable error.
> q - quit : User initiated end of playback before media asset completion.
> d - preloading : the player is loading assets ahead of starting in order to provide a fast startup. The expectation is that playback will commence at a future time. 
> This key MUST only be used for state-interval reporting mode.
>
