### ISSUE TITLE
Add control mechanisms for third-party endpoints in CMCD response and state-interval modes to handle overload and cost efficiency 

### ISSUE THREAD

**Issue by nicolaslevy** [cta-wave/common-media-client-data#149]
The CDN is prepared to scale with an increasing number of requests per second. If it receives CMCD via the request mode, it can decide whether to store the information or discard it.

On the other hand, the new modes (Response Mode and State-Interval Mode) are designed so that third parties can receive the information and decide what to do with it—whether to process it, store it, or discard it.

To give a control mechanism to these third-party endpoints in case of overload and to enable sub-sampling if needed to control costs, it is proposed to define a response that includes at least the following information:

* For Response Mode, allow the server to instruct the player to disable Response Mode.
* For State-Interval Mode, allow the server to specify how long the player should wait before sending the next update, setting a new Interval time and overriding the interval set by the application.

Example of a response for State-Interval Mode:
```
Response Code: 200 OK
Body:
{
    "sendOnStateChange": true,
    "setIntervalTime": 120
}

Also, an Ad tracking system that uses CMCD, could ask the player increase the "CMCD resolution" when an interstitial is detected ('int' key)

```
We could also explore using CMSD for this...

**Comment by nicolaslevy** [comment]
Also, an Ad tracking system that uses CMCD, could ask the player increase the "CMCD resolution" when an interstitial is detected ('int' key)

**Comment by PCaponetti** [comment]
Added the following text, will revisit next meeting:

```When reporting to a third party backend, a player SHOULD implement retry, backoff, and other mitigations for overload scenarios.```

**Comment by wilaw** [comment]
Paul: not the concern of CMCD. 
Nicolas: with ad tracking will know interstitial boundaries. What if user closes TAB - no clean exit. So use case is to enable a higher resolution in your reporting. 
Paul: decision for more resolution could be server or player side. So far player offers info, instead of server. Would be in config options of player. 
Chris: you could put config options in an annex
Gwendal: no way for server to configure client.
Paul: we try to stay away from that. 
Paul: maybe knowing interval is important? is that an over-complication. 
Will: the fact that we can have multiple destinations with different query times allows a higher frequency. Also DASH and HLS playlists could instruct player to make reports. 
Gwendal: can also use CMSDv2 to control CMCD. 
Paul: do we need to modify this issue? Dedicated GO-AWAY frame for example? 

Left spec with language "When reporting to a third party backend, a player SHOULD implement retry, backoff, and other mitigations for overload scenarios."

Will to make new issue on how to increase frequency just for ad reporting.
