### ISSUE TITLE
Buffer state questions

### ISSUE THREAD

**Issue by wilaw** [cta-wave/common-media-client-data#28]
[Filed on behalf of Pankaj]

During the CMCD call, we talked about whether to provide some workflow for how a player should implement ‘bs’ (buffer state) and ended up deciding that the spec in its current form is clear and hence, we don’t need to provide anything more.
 
I feel that it is missing details on some key questions:
1/ Is ‘bs’ to be maintained per object type, i.e. individual values for video-only, audio-only, subtitle, etc. segments?
>> PC: I think the answer here is ‘yes’.
 
2/ For the state of “buffer risk”, the spec says that it should be signaled “if trending downward and buffer length is less than 1 object/segment duration”. Is this object/seg duration the duration of the last downloaded segment, the one being downloaded, or any target duration that is listed in the manifest (EXT-X-TARGET-DURATION for HLS)?
>> PC: I think the answer is duration of last segment.
 
However, how does the answer change when CTE and ULL is in play?
What if the last segment is truncated due to start/end of Ad?
 
This makes me want to revise my answer to be the ‘target duration’.
 
Additionally, as a guideline, when ‘bs’ is signaled by player the ‘st’ (stream type as live or vod) should also be signaled.
 
Considering the above, while I am of the opinion that some guidance must be provided, maybe not in the main section of the CMCD spec but as addendum, etc.

**Comment by technogeek00** [comment]
1. Agreed individual object types make sense.

2. Though worth the thought that buffer risk for subtitle/captions and event tracks may be a different computation than one object size as in VOD they may vary significantly and usually represent a much larger time than a typical video/audio segment. Then again this may be less of a issue as the larger duration allows for longer lead times in download of the next piece.
2.

Perhaps the risk definition is more aligned with the buffer consumption rate (in stream time) being at risk of our running the observed download rate (also in stream time) given the duration of the tracks buffer.

Agreed this may be a good informative addendum rather than specification main text.

**Comment by dhassoun** [comment]
I definitely think this should be target duration not last segment duration. First off players dont generally know last segment duration anyways easily. They can know it of course but it is not a standard function of most players.

**Comment by wilaw** [comment]
Group made suggested changes to 'bs' value definition. 

1: startup/initializing (ends when initial buffer target is reached)
2: seeking (if client can not distinguish between startup and seeking then they SHOULD use 1:startup for seeking as well)
3: buffer risk (if trending downward and buffer length is less than 1 object/segment target duration)
4: buffer empty (if buffer is completely drained)

If the object type ‘ot’ key is sent along with this key, then the ‘bs’ value refers to the buffer associated with the particular object type. If no object type is communicated, then the buffer state applies to the current session.
