### ISSUE TITLE
Should header and query arg identifier be shortened to save data?

### ISSUE THREAD

**Issue by wilaw** [cta-wave/common-media-client-data#32]
Currently the header and Query arg payloads are identified by the "Common-Media-Client-Data" string. In logs, this looks like 

https://dash.akamaized.net/akamai/bbb_30fps/bbb_a64k/bbb_a64k_14.m4a?Common-Media-Client-Data=v%3D1%2Csid%3D%22f86948de-ba56-4423-ad06-20dbee793649%22%2Ccid%3D%22-977737661%22%2Cdid%3D%22dash.js-v3.0.3%22%2Cst%3Dv%2Csf%3Dd%2Cbr%3D67%2Cot%3Da%2Cd%3D4011%2Cmtp%3D5864%2Cdl%3D41675

To reduce verbosity and save data transmission costs (over millions of requests), should the identifier be shortened from

Common-Media-Client-Data

to

CMCD

**Comment by dhassoun** [comment]
good by me

**Comment by heff** [comment]
I like it for the query var but not the header name.

What are the risks of shortening it? Potential conflicts with exiting cache rules of the same name? Seems possibly but unlikely.

You could potentially bundle the spec version with the key name to help with that, `CMCD1=`. Though that could be annoying to parse.

**Comment by mnot** [comment]
Clashes aren't an issue for headers if you register the name; however, `CMCD` is pretty obscure. As a midpoint, perhaps `Media-Data`?

Regarding the query string, clashes are much more of a concern here, because there *is no global reservation of query parameters*; it's much more likely that someone, somewhere out there is already using this parameter (remember, the Web is big). See also [BCP 190](https://tools.ietf.org/html/rfc7320), which discourages this kind of practice in standards.

**Comment by wilaw** [comment]
We have since defined these new header names as a result of our move towards HPACK efficiency:

CMCD-Request : keys whose values vary with each request.
CMCD-Object : keys whose values vary with the object being requested.
CMCD-Status : keys whose values don’t vary with every request or object.
CMCD-Session : keys whose values are expected to be invariant over the life of the session. 

We have also shortened the query arg to "CMCD". We consider this sufficiently obscure.
