### ISSUE TITLE
What happens when server processing requirements are unmet

### ISSUE THREAD

**Issue by LPardue** [cta-wave/common-media-client-data#34]
Given my understanding, this issue may not be valid but please entertain me. 

Server processing requirements contains many clauses that are based on terminology imported from RFC2119. I understand that CMCD is not an IETF specification but in IETF normative requirements are generally oriented around interoperability of, in this case, client and server. Typically failure to meet a require can result in a request error, a connection error, or expressly no kind of error at all.

So I start to wonder about some of the requirements placed on the server and what a client expects to happen. For example, wrt to CMCD header and querystring: "a request ... MUST NOT carry both", "The server MAY assume that the payload is held as either a header or a query arg, but never both at the same time.". If I understand the intent of these combined statements you are saying "client MUST NOT send, server MAY treat reception as an error". If so, what does error look like? Request error, connection termination, silently dropping of request, silently dropping CMCD, picking one and passing it on, logging an error and passing both on, etc.

**Comment by wilaw** [comment]
We use RFC2119 language because we find it clear and unambiguous for defining expected conformance.

We agree that we need to add more specificity to how the server should behave in the face of misbehaving clients. So below we list all the ways a client may misbehave, and then we have added language to the spec  to address these situations. 

1. client sends incorrect header names or QA name
=> Server MUST only process these requirements when data is received via a valid CMCD header or query arg. 
2. Client sends invalid key names
=> Unknown keys, which the server does not understand, MUST be ignored. 
3. Client sends invalid values. 
=> Values which do not meet the structured data definition (such as an invalid token, or a string when an integer is expected) MUST be ignored. 
4. Client sends QA and header info. 
=> The server MUST process data from only the query arg or header channel, but never both for a given request. If any CMCD headers are present then any CMCD query arg information MUST be ignored.

**Comment by LPardue** [comment]
Thanks this looks like good clarification text.
