### ISSUE TITLE
Buffer state values open to interpretation

### ISSUE THREAD

**Issue by heff** [cta-wave/common-media-client-data#38]
In general, it'd be nice to have a better idea how each of these values might be used to help clarify the definitions.

I'm wondering if there's not a more direct way of describing the buffer state, closer to [HTML's readyState](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/readyState). The current values seem to combine player state and buffer state. For example, the buffer can be `buffer empty` and also `seeking`.

> seeking (if client can not distinguish between startup and seeking then they SHOULD use 1:startup for seeking as well)

Is the goal to capture the points where the player is starting with no data in the buffer? Why distinguish between seeking and startup?

What does seeking mean exactly? Is the player done seeking when it has the target frame, or does it need to finish filling its buffer first, and every segment loaded until then contains a `seeking` state?

> buffer risk (if trending downward and buffer length is less than 1 object/segment target duration)

Should we provide some examples of how to assume "trending downward"?

**Comment by wilaw** [comment]
We distinguish between start-up buffer state and seek-state as users are more tolerant of buffer issues during seeks than start-ups. Analytics may want to treat these independently. 

Debated language change for state [4] of 'bs'. Discussion TBC.

**Comment by heff** [comment]
That's great, it's just that seeking is an ambiguous state, from a player perspective at least. This makes sense to me if I think of it in terms of "why am I making this request", rather than trying to define the player states.

[player is attempting to play and playhead is *not* moving forward yet]
1: startup/initializing - Player does not have enough data to start playing
2: seeking - The user requested an unbuffered (or partially buffered?) region of the video. When the buffer is full enough that the playhead can move forward the player is no longer 'seeking'.

[playhead is moving forward]
3: buffer risk - Playhead is continuing forward for the user but this is a warning to the server

[playhead was moving forward]
4: buffer empty - Player for some reason didn't make this request before it ran out of data.

**Comment by wilaw** [comment]
After much debate, we have two changes that we hope address the issue of ambiguity of the prior definitions balanced with the clarity and usefulness of the information being provided. 

1. Add in a new key field called Startup. 

Startup | su | CMCD-Request | Boolean | TRUE if the object is needed urgently due to startup, seeking or recovery after a buffer-empty event. The media SHOULD not be rendering when this request is made. This flag MUST not be sent if it is FALSE.

2. Revise the 'bs' field to be Buffer Starvation (instead of buffer state). 

Buffer starvation | bs | CMCD-Status | Boolean | TRUE if the buffer was starved at some point between the prior request and this object request results in the player being in a rebuffering state.  This value MUST not be sent if it is FALSE. If the object type ‘ot’ key is sent along with this key, then the ‘bs’ value refers to the buffer associated with the particular object type. If no object type is communicated, then the buffer state applies to the current session.

**Comment by heff** [comment]
Makes sense to me, thanks! 👍
