### ISSUE TITLE
Version unsupported by server

### ISSUE THREAD

**Issue by heff** [cta-wave/common-media-client-data#40]
It should probably be clear what servers should do if a player sends a CMCD version number higher than what the server is aware of. 

The spec already says a server should ignore keys it doesn't understand, so a version bump would only be required with a breaking change, so servers should ignore the entire data set in that case. (And ideally alert themselves that they need to upgrade their support.)

The risk being that servers continue to try to parse the values with breaking changes.

**Comment by wilaw** [comment]
Good point. IMO servers should ignore the entire data set if the signaled version is greater than they understand, as they cannot know which fields have been modified or deprecated. We should suggest that they also log the version incompatibility so that there is some record of why the data is not getting logged.

**Comment by wilaw** [comment]
Added "Servers MUST ignore the entire data set if the signaled version is greater than they understand, as they cannot know which fields have been modified or deprecated. Servers SHOULD log the version incompatibility so that there is a record of why the data is not getting logged." to server processing requirements.
