### ISSUE TITLE
Header syntax

### ISSUE THREAD

**Issue by mnot** [cta-wave/common-media-client-data#41]
Have you considered using Structured Headers to define your syntax? It should be an RFC soon (just about to go to IETF Last Call):
  https://httpwg.org/http-extensions/draft-ietf-httpbis-header-structure.html

It would help interoperability, and a possibility of a future binary encoding:
  https://mnot.github.io/I-D/binary-structured-headers/

**Comment by wilaw** [comment]
Yes, in fact this was raised by Chris Lemmons as prior issue https://github.com/cta-wave/common-media-client-data/issues/29. We modified our structure and should be complaint with the https://httpwg.org/http-extensions/draft-ietf-httpbis-header-structure.html#dictionary requirements of the header structure spec. 

We debated referencing the draft header-structure spec in our document, but decided to omit it since it was not yet a reference-able RFC. Should we signal compliance intent by referencing the draft?

**Comment by mnot** [comment]
That would be best, yes; otherwise it's not clear what implementations should do in the corner cases.

**Comment by mnot** [comment]
Also, there are some errors in the examples:

* Throughout, `”`('smart' quotes) are used instead of `"` (straight quotes)
* `mtp:25430` -- `:` is not legal in keys; do you mean `mtp=25430`?
* `com.example-myKey=myValue` -- keys need to be all-lowercase
* `nrr=12323-48763`-- this isn't a valid integer. perhaps `nrr="12323-48763"`?

**Comment by alficles** [comment]
Good catch. The colon is indeed unintentional, the previous separator was a colon. And the quotes were missed as well. That's defined as a string type, which needs the quotes. I'd missed the capital in the key, too. I blame either Apple or Microsoft for the smart quotes. :)

Is there an example of a proper reference for a draft spec? I know there's some guidance around how NOT to reference it, but it is in last call.

**Comment by mnot** [comment]
Regarding a reference - generally, just append "Work in Progress." 

FWIW, you can check the header values for correctness using [this implementation](https://pypi.org/project/http-sfv/) on the command line - see the README.

**Comment by wilaw** [comment]
1. Added language to payload definition to signal our intent to be compliant with https://www.ietf.org/id/draft-ietf-httpbis-header-structure-18.txt.
2. Added draft reference to https://www.ietf.org/id/draft-ietf-httpbis-header-structure-18.txt as work-in-progress.
