### ISSUE TITLE
Impact on header compression efficiency

### ISSUE THREAD

**Issue by mnot** [cta-wave/common-media-client-data#44]
It appears that while many parts of the header value are going to be stable over the life of a connection (e.g., `cid`, `did`, `ot`, `sf`, `sid`, `st`), there are some that will not be -- in particular, `nrr`, `nor`, `mtp`, `d` and I'm sure others.

When a header like this is sent on a HTTP/2 (and soon to be HTTP/3) connection, it doesn't interact well with the HPACK (soon to be QPACK) compression algorithm, because they act at the granularity of an entire header value. The outcome is lower compression efficiency, which is especially critical for request headers.

See [this article](https://www.mnot.net/blog/2018/11/27/header_compression) for more information.

Have you considered breaking out the more dynamic information into one or more separate headers?

**Comment by wilaw** [comment]
We like the conciseness and simplicity of having all fields within a single header, so we need to judge the relative cost of the compression inefficiency versus the implementation complexity (for client and server) in using multiple header fields. How significant is the lower compression efficiency induced by the mutating fields? Is it 1.5% less or 20% less?

**Comment by mnot** [comment]
It depends on how the header is used, but from what I can tell your headers will have a lot of variance over time, in some of the fields, to the degree that it will change on each request (or almost that much). 

If that's the case, you won't get any HPACK/QPACK compression for this header -- at all. Additionally, implementations might still try to compress it, which is worse, because it will take up space in the dynamic table -- impacting the compression efficiency of other headers (potentially to a severe degree).

**Comment by wilaw** [comment]
For those joining this thread who want some background on HPACK, read Mark's article here: https://www.mnot.net/blog/2018/11/27/header_compression.

To address this issue, we have three proposals that we would like feedback on:

_**Solution A: Serialize the existing header.**_
It could be transmitted as
Common-Media-Client-Data: sid=”6e2fb550-c457-11e9-bb97-0800200c9a66”
Common-Media-Client-Data: d=4004
Common-Media-Client-Data: rtp=15000

Due to HTTP's header combination rules, this is syntactically equivalent to the currently proposed implementation of 

Common-Media-Client-Data: sid=”6e2fb550-c457-11e9-bb97-0800200c9a66”,d=4004,rtp=15000,mtp:25430,br=3200,bs=1,ot=v

but the advantage is that the serialized implementation does not create a combinatorial explosion in the HPACK dynamic table. There is one danger in that a forwarding proxy might try to do the client a favor and combine these headers in to a single field as it forwards the request. This danger is reduced with TLS transmission which would prevent such header reconfiguration. An additional advantage of this approach is that the 'access-control-allow-headers' response CORS header need only include the single header name of 'Common-Media-Client-Data'. 

_**Solution B: Each field would be carried in its own header.**_
All headers would have a consistent prefix of "CMCD-", prefix followed by the field identifier:

Common-Media-Client-Data-sid: ”6e2fb550-c457-11e9-bb97-0800200c9a66”
Common-Media-Client-Data-d: 4004
Common-Media-Client-Data-rtp: 15000
..
Custom fields could be added using the same prefix.

Concerns:

- Allow-request-headers must be significantly increased on server-side, even if the client does not support CMCD. For example, it would look like - access-control-allow-headers: origin,range,hdntl,hdnts,accept-encoding,referer,Common-Media-Client-Data-sid,Common-Media-Client-Data-d,Common-Media-Client-Data-rtp
- If a server does not advertise support for a field via the access-control-allow-headers, should the client stop sending it? 



_**Solution C: Drop headers altogether**_
Are request headers architecturally the wrong vehicle to be communicating this information? What if CMCD only allowed query args for data transmission?

**Comment by alficles** [comment]
I'll start with the two I don't like: A and C. A is fragile and likely to break in some genuinely annoying ways. And I don't like C because headers are actually a good place for this data.

There's a middle ground on B, though: break up the headers into conceptual groups. A quick bucketing suggests something like this:

```
Common-Media-Client-Data-Object: br=0,cid="qq",d=300,ot=v
Common-Media-Client-Data-Conn: bs=1,dl=9,mtp=7000,rtp=700
Common-Media-Client-Data-Session: sid="quux",st=v,sf=h,pr=1
Common-Media-Client-Data-Next: nor="/",nrr="0-1024"
```

I think option B is ok, but if folks would prefer fewer headers, there's a middle ground as well. The idea is to set the buckets up so that the things that are likely to change together are all in the same bucket.

**Comment by mnot** [comment]
FWIW - the middle ground makes sense, especially if those values are likely to be "sticky" together, as it appears to be on the surface (I haven't looked into it deeply).

One other thing - that's a very long proposed header field name, and it takes up room in the dynamic table too (as well as bytes on the wire). I'd suggest something like `CMCD-*`.

**Comment by alficles** [comment]
Yeah... I like `CMCD-*` better as well. Might be worth hammering out which header would work best with which data.

**Comment by wilaw** [comment]
Group decision is to breakout current header in to 4 new buckets, with fields allocated based upon the expected degree of variance within a given session. Also agreed to shorten header name. 

CMCD-Request: dl, mtp, nor, nrr,
CMCD-Object: br, od, ot, 
CMCD-Status: bs, rtp
CMCD-Session: cid, pr, sf, sid, st, v, 

Need to modify doc to implement his change+ add explanation of these bucket choices.

**Comment by mcpv** [comment]
Should we round certain values to promote hashing? For example, if I'm collecting "mtp" (measured throughput) and the values differ by relatively insignificant digits (1540, 1571, 1506, 1528, 1583, 1592, 1601, 1505, etc.), there would be virtually no compression because each of these will have a unique value in the hash table. Pairing this with one or more attributes that also vary in a similar way will make it even harder. However, rounding those values (i.e., 1500 & 1600) would likely provide some compression. Is this a worthwhile trade-off?

**Comment by wilaw** [comment]
Multiple headers were implemented and document updated. Agreed to round mtp and rtp to nearest 100kbps. Added guidelines for how custom keys should be assigned to headers.
