### ISSUE TITLE
Note on client privacy while using CMCD

### ISSUE THREAD

**Issue by wilaw** [cta-wave/common-media-client-data#45]
The device-id and content-id fields are invariant when then same content is played from the same device and hence could be used as fingerprinting dimensions by a 3rd party. Although both are optional, any client implementation should weigh the risks of fingerprinting versus the benefits of performance analysis of device and/or content problems. 

Request is to add language to the specification under the "Security Considerations" section highlighting this risk, and also clarifying that no PII should be ever be included in any value that is being sent.

Additional, team should review CMCD against GDPR requirements.

**Comment by mnot** [comment]
Just noting that if this were to go through one of the relevant standards bodies -- IETF or W3C -- this likely wouldn't be enough to pass privacy review. The bar has been raised considerably, and you might find that if a fingerprinting / tracking vector is introduced, browsers will actively work to quash it.

**Comment by wilaw** [comment]
Group meeting decided to remove DeviceID field due to the raised fingerprinting concerns. We retain ContentID, with the argument that the request URL is already visible to observers and communicates similar information to CID field, therefore removing ContentID has no benefit in reducing any fingerprinting surface.

**Comment by alficles** [comment]
Looking over the remaining fields, the only fingerprinting surface I see left is the CMCD Version. It's currently pegged at 1, but may or may not be omitted. The act of including it or not could leak information about the player. Maybe we should make version "MUST NOT" include?

**Comment by mnot** [comment]
Removing DeviceID is good, but not sufficient.

Fingerprinting is the ability to identifier the user (or more accurately, their specific browser instance) and correlate a user’s browsing activity within and across sessions by combining bits of entropy about them. See [this](https://w3c.github.io/fingerprinting-guidance/) for more.

The threat model has to assume a hostile Web site -- i.e., what could the site do to thread together a users activities using the information you expose? ContentID could certainly be used in that fashion, as could many of the other bits of data; browsers are extremely conservative about adding new bits that can be used in this way as a result.

If the information is cleared when the user purges state on the browser (cache, cookie, etc.), you should be good; you're inside the envelope that their security model provides, as it were. However, if this information is stored by browser extensions across that, or in non-browser software, it's not addressed.

So really, it comes down to the deployment model -- is this information always stored and used through the "normal' browser mechanisms (e.g., exposed by JS), or do extensions and non-browser applications sometimes set/access it on behalf of the user?

**Comment by alficles** [comment]
ContentID information is effectively stored in the URI. It identifies which content the object is stored in. The vast majority (maybe all?) of origins have a URI that looks like a variation of this: "http://origin.example.com/content-id/fragment-id". This just allows a player to break out the content-id for the CDN's benefit so it doesn't have to parse it out of the URI. And even if the URI doesn't include the content-id, by having globally unique fragment-id, for example, I still don't think it's a fingerprinting risk because it's fundamentally tied to the specific content being requested.

A hostile website could issue a request for a given piece of content, but it's up to the website to provide the content-id for the content.

In fact, as it stands, the fingerprinting risk _only_ exists when a media player is implemented as an extension. It's much more common for the player to be provided by the website itself, in which case there's no fingerprinting risk because the player only has access to the data already accessible in the browser.

We'd like extensions that naively implement things not to create fingerprinting risks, though, so DeviceID was dropped. That would have exposed the information "has extension that has a specific DeviceID", which is pretty informative, especially if the extension was uncommon. There's only so much you can do with an extension that has "modify data on all websites" permission, though, which is what such a player would generally need.

I think all the other information in the spec is already obtainable via JS in the browser, which is unsurprising because it's designed to be implemented primarily as a player delivered by a website to viewers.

**Comment by wilaw** [comment]
@mnot  - your question here

`So really, it comes down to the deployment model -- is this information always stored and used through the "normal' browser mechanisms (e.g., exposed by JS), or do extensions and non-browser applications sometimes set/access it on behalf of the user?`

leads me to comment that we are not talking about JS browser APIs with this spec. It can be used by any client, especially ones that are not executing within browsers.  I wonder how you envisage a bad actor taking advantage of the data transmitted via the CMCD standard to fingerprint? It is a data format standard for communication happening between a player application and a CDN. _There is no API to invoke_. With a TLS request, the only recipient of the data is the CDN server. The CDN already sees every single request that the player makes, so deprecating contentID while the CDN logs every media segment requested and can thus identify the content precisely, seems pointless. How would fingerprinting by a malicious 3rd party even work? Is the concern that the CDN is actually the malicious party?

**Comment by mnot** [comment]
I apologise if this is vague; I'm not familiar with the concrete deployment scenarios you're targeting for this.

Fingerprinting isn't specific to APIs; that's just how it's often done in browsers. The threat model is that the _server itself_ is the attacker (whether that's a CDN or an origin), and their overall purpose is to identify the client against the users' will (as expressed by clearing cookies and other client state).

So, if content ID is writable by the server (or another party) and is then sent back in requests, it can be used as a way to identify the user on the site. 

In a browser deployment, that's fine, as long as it doesn't persist beyond the user clearing state (cookies, cache, etc.) -- e.g., in a plugin or other extension.

In a non-browser deployment, it depends on the user expectations for the system, and the controls exposed to them. 

It's not just cookie-like mechanisms; every bit of information that's sent in requests has the potential to identify the client; for example, in browsers, the screen width reported adds bits of entropy. Since this specification is defining information to be sent from clients to servers, it seems relevant.

That doesn't mean that you need to drop all of that information. It may be that it's adequate to document this risk, and state that browser extensions and  non-browser applications need to consider the privacy implications of exposing this information, with appropriate references and illustrations. An evaluation of the risk associated would help enormously.

**Comment by alficles** [comment]
> Fingerprinting isn't specific to APIs; that's just how it's often done in browsers.

Yup. The basic idea is to get the client to make requests in a way that reveals information about themselves they didn't intend to reveal.

There are three main deployment strategies that I envision for this. First is the JS/HTML5 player in the browser. This is accomplished entirely by having the server send the player to the client and has the same fingerprinting surface as any web content.

Second, browsers may have extensions for playing various types of content. Some of these extensions may implement this specification. In such a case, the kind of request made could reveal the version of the extension handling the request, or possibly leak other information about the extension. Even things like "what order are some fields served in" can provide fingerprinting surface here. Worse, the site need not even be an overt media site to take advantage of this, since a media-playing plugin might be induced to run in a non-obvious way. There's only so much you can do here, since a media plugin that had "modify all web pages" permission can provide as much fingerprinting surface as it wishes. Nevertheless, with DeviceID dropped, all the remaining fields depend on either the connection or request itself, not traits reasonably attributable to the processing entity (the plugin, in this case). I think the main remaining fingerprinting surfaces are the choices embedded in the "MAY"s and, in the future, the version number.

And lastly, it might be implemented by a standalone player that runs as a program on a general purpose or specialized device. All the same caveats from the extension apply, but the scope is rather significantly reduced because an arbitrary non-media site won't be able to leverage a media-playing program that isn't capable of processing it.

And maybe I'm underestimating the fingerprinting surface of the connection itself. That is to say, things like "how fast can I transfer files" do provide a bit of entropy that you might use against a client. But anything that can request transfers can get at that information already.

It might be useful to enforce a serialization order, though, to reduce the entropy revealed there.

**Comment by wilaw** [comment]
Agreed to a SHOULD for alphabetical sequencing of key/value pairs to reduce fingerprinting surface.
