### ISSUE TITLE
Question on current buffer length

### ISSUE THREAD

**Issue by wilaw** [cta-wave/common-media-client-data#5]
re "The length, in milliseconds of forward-buffered playback time until a gap is present. This value SHOULD be the minimum of the audio and video buffers if the client is playing synchronized content. "

Stockhammer - Why would you add to a video request the buffer length of the audio and vice versa. It should be the buffer length for what you request.

Law - No, because this buffer length field is intended as an indication of whether the player is about to rebuffer or not. If the player has 5s of video buffer and only 1s of audio buffer, it is about to stall since it needs both buffers for synchronized playback. So we always want to send the minimum of the two buffers, since this the one that will determine a stall or not.

Stockhammer - How this help the CDN?

**Comment by acbegen** [comment]
Will, in your example, if the request is for video, indicating a buffer of 1s would be incorrect. Each request should indicate the current buffer for that respective media.

**Comment by dhassoun** [comment]
updated to BufferState (bs - enum): 
0: nominal - do not send
1: startup/initializing (ends when initial buffer target is reached)
2: seeking (if client can not distinguish between startup and seeking then they should use 1:startup for seeking as well)
3: buffer risk (if trending down downward and buffer length is less than 1 object/segment duration)
4: buffer empty (if buffer is completely drained)

Supplied on manifest and segments/objects when applicable.

When applicable specify values that pertain to that specific media, otherwise provide the minimum value.
