### ISSUE TITLE
Buffer state could be % (Comment from Streaming Video Alliance)

### ISSUE THREAD

**Issue by NEOAdvancedTechnology** [cta-wave/common-media-client-data#52]
Below is a comment on draft CTA-5004 Common Media Client Data from the Streaming Video Alliance:

Buffer State – we think need a state for OK so a state between 2 & 3 – maybe this could be %

**Comment by wilaw** [comment]
Buffer state is meant to indicate a problem with buffer. We indicate "If the buffer state is nominal during normal play, this key SHOULD not be sent".

Also, different players have different thresholds for what constitutes a buffer problem, so a % value would be difficult for a CDN to determine.

We have also added a new buffer length key 'bl' since community review. Taking those values / max(bl) would give the % value you are looking for. 

Updated key value field definition to "This key is used to indicate an abnormal buffer state.  If the buffer state is normal and expected, this key SHOULD not be sent."
