### ISSUE TITLE
Section 5 "Security Considerations" should explain in more detail about threats and countermeasures taken

### ISSUE THREAD

**Issue by mbergman42** [cta-wave/common-media-client-data#61]
Reviewing Section 5 _Security _Considerations_, it is very terse.  By comparison, the W3C _Privacy Self-Assessment Questionnaire_ and RFC 3552 _Guidelines for Writing RFC Text on Security Considerations_ recommend a more complete discussion of threats to security and privacy.  We are not obliged to follow these other guidelines, but the following does borrow from their experience.  

Recommend renaming this section to _Security and Privacy Considerations_ and extending the text.  Suggested new text follows, incorporating much of the existing text but adding more explanation and threat discussion:

### 5. Security and Privacy Considerations

**5.1 Threat Environment**
The data transmitted as defined by this specification is passed between a client device and a Content Delivery Network (CDN), as described in Section 2, Data Transmission Modes.  Data is exchanged over HTTP/HTTPS during the regular process of a media client requesting content. There is no new threat environment created by developers following the standard defined in this document. The HTTP Request Headers and Query Arguments utilized for data transmission are mature and established technologies for data transmission over the web. Transport Layer Security (TLS) provides can provide confidentiality and integrity for data during transmission. 

**5.2 Threats to the Server**
A malicious client may inject false data.  This tactic may be part of replay, message insertion, or modification attacks.  If the server-client communication is delivered over HTTP, then man-in-the-middle attacks are feasible. Use of HTTPS for communications mitigates these attacks. All server responses are optional, which aids in server-based protection strategies. The server is not required to take any action upon receiving CMCD data. 
Some limited denial-of-service amplification opportunity exists for malicious clients utilizing the next-object-request key. Requiring the next object to be a relative path to the current request, along with the prefetch operation be optional for the server, helps mitigate this amplification. 

**5.3 Threats to the Client**
Privacy concerns resulting from successful eavesdropping and man-in-the-middle attacks in this threat environment indicate the need to strictly limit device-identifiable data.  Therefore, fingerprinting opportunities have been minimized; see for example sections 3.1 and 3.2.  Identification Confidentiality of content, as described above, is subject todependent upon protocol-layer protections since the playback client must by definition request playback of specific content pieces to operate.
Defense against malicious content injected via man-in-the-middle, message insertion, or message modification attacks is likewise dependent upon protocol-layer protections. HTTPS is generally recommended over HTTP, when applicable, for all CMCD data transmissions over the web. 

**5.4 Specific Mitigations**
As discussed above, the specification does not expose any security issues that are not already exposed to a client making media object requests or to an edge server which answers all incoming requests. A number of steps have been taken to mitigate security and privacy concerns:

1. The ‘nor’ key value must be a relative path to the current request. This makes it harder to inject false requests to arbitrary objects.
2. Only one object can be requested by the ‘nor’ key value - this lowers amplification opportunity.
3. All requests to the server are optionally executed by the server, meaning that a server can ignore them for security concerns (such as a rate-based threshold being exceeded) and still be compliant with the specification.
4. Session ID is a GUID which never repeats for a particular user.
5. Measured throughput, requested maximum throughput, deadline and buffer length are bucketed to reduce fingerprinting surface.
6. Key-value pairs should be sequenced in alphabetical order to reduce fingerprinting surface.
7. Personally Identifiable Information fields, such as IP address, cookie information and location data, are intentionally not carried by the specification.

**Comment by wilaw** [comment]
Group editing of proposal:

5. Security and Privacy Considerations
5.1 Threat Environment
The data transmitted as defined by this specification is passed between a client device and a Content Delivery Network (CDN), as described in Section 2, Data Transmission Modes. Data is exchanged over HTTP/HTTPS during the regular process of a media client requesting content. The HTTP Request Headers and Query Arguments utilized for data transmission are mature and established technologies for data transmission over the web. Transport Layer Security (TLS) can provide confidentiality and integrity for data during transmission.

5.2 Threats to the Server
A malicious client may inject false data. This tactic may be part of replay, message insertion, or modification attacks. If the server-client communication is delivered over HTTP, then man-in-the-middle attacks are feasible. Use of HTTPS for communications mitigates these attacks. All server responses are optional, which aids in server-based protection strategies. The server is not required to take any action upon receiving CMCD data.
Some limited denial-of-service amplification opportunity exists for malicious clients utilizing the next-object-request key. Requiring the next object to be a relative path to the current request, along with the prefetch operation being optional for the server, helps mitigate this amplification. 

5.3 Threats to the Client
Privacy concerns resulting from successful eavesdropping and man-in-the-middle attacks in this threat environment indicate the need to strictly limit device-identifiable data. Therefore, fingerprinting opportunities have been minimized; see sections 3.1 and 3.2. Identification confidentiality of content, as described above, is dependent upon protocol-layer protections since the playback client must by definition request playback of specific content pieces to operate.
Defense against malicious content injected via man-in-the-middle, message insertion, or message modification attacks is likewise dependent upon protocol-layer protections. HTTPS is strongly recommended over HTTP, when applicable, for all CMCD data transmissions over the web.

5.4 Specific Mitigations
As discussed above, the specification does not expose any security issues that are not already exposed to a client making media object requests or to an edge server which answers all incoming requests. A number of steps have been taken to mitigate specific security and privacy concerns:

- The ‘nor’ key value must be a relative path to the current request. This makes it harder to inject false requests to arbitrary objects.
- Only one object can be requested by the ‘nor’ key value - this lowers amplification opportunity.
- All requests to the server are optionally executed by the server, meaning that a server can ignore them for security concerns (such as a rate-based threshold being exceeded) and still be compliant with the specification.
- Session ID is a GUID which is highly unlikely to repeat for a particular user.
- Measured throughput, requested maximum throughput, deadline and buffer length are bucketed to reduce fingerprinting surface.
- Key-value pairs should be sequenced in alphabetical order to reduce fingerprinting surface.
- Personally Identifiable Information fields, such as IP address, cookie information and location data, are intentionally not carried by the specification.


Discussion - what about players sending malicious data? Should players be able to sign headers/query args? Would client certificates be useful?

**Comment by wilaw** [comment]
Updated section 5.
