### ISSUE TITLE
Quality Level (ql) of rendition (contribution from the Streaming Video Alliance)

### ISSUE THREAD

**Issue by NEOAdvancedTechnology** [cta-wave/common-media-client-data#64]
(This comment is a contribution from the Streaming Video Alliance Quality of Experience WG)

Proposing a new value named Quality Level (ql) that reports the quality level of the rendition whose segment or part is being requested, relative to all the available rendition quality levels for the content title. Values range from 0 to 100, where 0 indicates that the rendition is the lowest quality level and 100 indicates that the rendition is the highest quality level available for the content title.  The integer value is calculated by ranking the available renditions by bit rate from lowest to highest, and then dividing the index of the player requested rendition by the total number of offered renditions, and multiplying by 100.

As an example, if a title has an ABR stack with 3 encoded bit rates (renditions) available, ranked from lowest bit rate to highest: 1.0 Mbit/s, 2.0 Mbit/s, and 5.0 Mbit/s, and the media segment being requested is associated with the 2.0 Mbit/s rendition, then ql would be 66 = int((2/3)*100).

Servers (CDNs) can infer that clients consistently requesting media segments with ql values of 100 are experiencing good performance and serving the viewer the highest available quality.

**Comment by wilaw** [comment]
one problem with this metric is that it is not comparable between presentations. Consider stream A which has bitrates of 1M, 2M, 3Mbps and Stream B which has 1M, 2M, 5M, 8M, 10MB.

A client playing the 2Mbps bitrate of A would report a quality score of 66%
A client also playing the 2Mbps bitrate, but of B would report a quality score of 40%

Both clients are actually delivering the same quality to the end-users, but the quality scores suggest otherwise. "QulaityLevel" may just be an inappropriate name. The metric is really indicating bitrate ladder utilization. We already have a key for bitrate level being played, so this data could inferred from existing data. 

Also, many players limit the bitrate based upon the size of rendering window. Only if the user goes full screen for example, do they unlock the higher bitrates (resolutions). Therefore you cannot necessarily infer poor performance from a low score as it could simply be that the user has a player in the smaller window.

**Comment by wilaw** [comment]
Chris - could be indices below max available for that size. Do we care about diff between 66 and 40? 
Cooper - HLS has a "score" for a given bitrate - AVC vs HEVC for example. Highest quality would be bitrate with highest score. Cannot compare scores across encoders. 
Thomas - not really about visual quality, intended more to reflect delivery performance. 

How do we compare across streams? Could scale by max client desired bitrate. 

CDN at edge does not know what bitrates are available, or performance of other streams. 

ATT StreamSaver, limits bandwidth to 1.5Mbps - can interfere with interpretation. 

_Redefine - Bitrate Percentage. Current bitrate divided by the maximum bitrate available given codec, resolution and bitrate limits set by the client, multiplied by 100. Intended as a delivery metric._ 

As an example, if a title has an ABR stack with 3 encoded bit rates (renditions) available, ranked from lowest bit rate to highest: 1.0 Mbit/s, 2.0 Mbit/s, and 5.0 Mbit/s, and the media segment being requested is associated with the 2.0 Mbit/s rendition, then bp would be (2/5)*100 = 40. 

As an example, if a title has an ABR stack with 5 encoded bit rates (renditions) available, ranked from lowest bit rate to highest: 1.0 Mbit/s, 2.0 Mbit/s, and 5.0 Mbit/s, 8Mbps, 10Mbps and the media segment being requested is associated with the 2.0 Mbit/s rendition, then bp would be (2/10)*100 = 20. 

As an example, if a title has an ABR stack with 5 encoded bit rates (renditions) available, ranked from lowest bit rate to highest: 1.0 Mbit/s, 2.0 Mbit/s, and 5.0 Mbit/s, 8Mbps, 10Mbps. The client is limiting itself to 8Mbps bitrate due to screen size and the media segment being requested is associated with the 2.0 Mbit/s rendition, then bp would be (2/8)*100 = 25. 

Imagine client with 1,2,3Mbps at AVC and then 2,3 4 Mbps at HEVC. So if it is playing 2Mbps AVC, it should report 66. If it is playing 3Mbps AVC, it should report 100. If it is playing 3Mbps HEVC, it should report 75. 

Would it be simpler top report the max desired bitrate? 
Cooper - how many switch ups failed? 
Chris- are players experiencing degraded quality of experience that is not signalled by rebuffers. How would a CDN use this data? What is the correlation between a low score here and then signaled measured throughput?

**Comment by wilaw** [comment]
Chris - thing CDN cares about   - is client experiencing issues not detected by rebuffers. 
Will- what about using mtp ? 
Chris - clients will limit their read rate.Request large object, use 0 win to limit server send rate. 
Need metric to indicate that we are not delivering the top bitrate that the client wants.
Agree that client could report top bitrate of the codec it is using if it had infinite bandwidth.
Client reports mtp of 15000, bitrate of 5000 and a top bitrate of 10000. Could be dropped frames, CPU load etc that prohibits client from switching up. 
Defined new key/value pair

**Top bitrate | tb | CMCD-Object | Integer Kbps | The highest bitrate rendition in the manifest or playlist that the client is allowed to play, given current codec, licensing and sizing constraints.**
