### ISSUE TITLE
Should the top bitrate field (and buffer length etc.) depend on the request type?

### ISSUE THREAD

**Issue by mgreve-akamai** [cta-wave/common-media-client-data#76]
We have seen players that sent one top bitrate for audio requests, and another top bitrate for video requests. The top bitrate  sent for audio requests is the top audio bitrate in the manifest and the top bitrate sent for video request is the top video bitrate in the manifest.

The spec isn't totally clear what's expected in this case: "The highest bitrate rendition in the manifest or playlist that the client is allowed to play, given current codec, licensing and sizing constraints.".

It would be good if the spec could clarify in general what's the expected top bitrate sent on each type of request. The same comment also applies for other fields, e.g. the player may have a separate buffer for audio and video, and hence could provide two different values. For the buffer length, this is what the spec says: "The buffer length associated with the media object being requested.". This hints at providing two separate values, but we haven't actually seen players provide two values in the wild, e.g. https://reference.dashif.org/dash.js/nightly/samples/advanced/cmcd.html provides only one value for buffer length, irrespective of whether it's an audio and video request.

**Comment by wilaw** [comment]
Short answer is yes, the top bitrate field should reflect the media type if it is communicated, or the video bitrate if the media type is not communicated. For example, if you have two audio bitrates (32, 96kbps) and four video bitrates (500,1000,5000,10000 kbps) then you might report 96 was the top bitrate for an audio file request and 10000 as the top bitrate for a video file request. As an additional nuance, if the 10000kbps representation is 4K and can only be used by the player if it is connected to a 4 monitor, then for a player which is NOT connected to a 4K monitor, it should report 5000 as the top bitrate as that is the top bitrate it could play if it had infinite bandwidth.

The same is true for buffer length. It should relate to the type of media object being requested. The reason for this is that if you only report the video buffer length, then you miss many players that stop because the audio buffer is empty. We debated having the player send only the lower of the two buffer lengths, as that would correlate well with stalling, however we are losing information at that point. Any parsing system, such as GhoLo, can intelligently process both buffer lengths and propose a minimum buffer length in its report if it chooses. 

If dash.js is sending the same buffer length for both audio and video object requests, then that is a bug in its CMCD implementation.
