### ISSUE TITLE
Toggle on/off sending of CMCD data

### ISSUE THREAD

**Issue by pankaj-giter** [cta-wave/common-media-client-data#81]
Ask: A flag to toggle on/off the sending of CMCD data by players.

Rationale: The capability to enable a specific functionality, in this case CMCD data by players, is an important dev-ops aspect of any organization. For CMCD, the data can be generated by any/all players in the ecosystem. This data is received at the CDN layer for not just logging but also making important optimizations that can impact quality of playback for one or more playback sessions.
As new players start adopting CMCD, it is conceivable that there could be buggy behavior producing invalid data, which may have 0 to significant impact on systems that process and consume this data.

A flag to toggle CMCD at the players is an ideal dev-ops capability.

Solution Proposal:
1. A flag to toggle on/off generation and sending of CMCD data at the players.
2. Flag should additionally indicate the version of CMCD to toggle on/off. Example: cmcd-toggle=off to toggle CMCD irrespective of version, cmcd-v1-toggle=off  to toggle a specific version causing player to fallback on previous version OR better yet cmcd-v1-toggle=on to toggle on just v1 version of the CMCD data.
3. This flag can be specific as a query param in the playback URL (HLS master or DASH MPD) as generated by the content provider
4. This flag can also be generated by the CDN and sent in a response back to player.
5. Default behavior will be to always send CMCD data.
6. The expected behavior for player is to stop generation and sending of CMCD data for all subsequent playback requests for the current playback session.

**Comment by wilaw** [comment]
CMCD can be turned on or off by any number of mechanism, but these are not the domain of CMCD to define. 
AlexG - prefer to add ability to manifest to toggle CMCD status, versus an intermediary. Also multi-CDN issue. 
One suggestion would be to extend CMSD to have a flag to run CMCD on/off.

**Comment by PCaponetti** [comment]
@pankaj-giter are you able to say more about the use case here? Is it just that on/off is a capability that should be available in all features, or is there something specific about CMCD data that makes this capability more desirable? Is it the worry that there are too many bytes? Is it that data might be getting where it shouldn't go?

I ask because my guess is this might require an update to the CMCD spec and also the CMSD spec (to send the trigger) which is a big lift, and there might be a better way to satisfy the use case. It also opens a can of worms around the operation of CMCD where to date we've only concerned ourselves with the API of data.

**Comment by nicolaslevy** [comment]
I think Alex Giladi can provide additional information related to the work they are doing in DASH to include in the MPD signaling for activating/deactivating CMCD.
