### ISSUE TITLE
Provide a CMCD flag that authorizes the sending of CMSD headers in origin/cdn responses on a request by request basis.

### ISSUE THREAD

**Issue by wilaw** [cta-wave/common-media-client-data#82]
[On behalf of Josh Evans]  Referencing issue: https://github.com/cta-wave/common-media-server-data/issues/12 - when we kick off CMCD v2 consider adding a flag set request by request (either as a querystring or header field). This will require explicit guidance about propagating this value (or a discrete set of values) from CDN through CDN middle tiers through to the origin.

**Comment by nicolaslevy** [comment]
Here are some notes and thoughts after reading the ticket https://github.com/cta-wave/common-media-server-data/issues/12:

- I believe this would be the first flag of a configuration type rather than a player operation data type. That said, if we agree to add this flag, would it make sense to recommend not logging it?
- In the original ticket, it is mentioned that versioning could also be considered. What happens if, in the future, we want to enable CMSD v2 instead of v1? Would this require a new flag, or could we send the CMSD version to be enabled? For example, cmsd=1, cmsd=2 to indicate the cmsd version to enabled, and cmsd=0 to turn it off.
- If we add this flag, does it make sense to send it request by request, or should it serve as a flag for the server to turn on/off until further notice, with the aim of not increasing the size of headers/query parameters with each request?

**Comment by PCaponetti** [comment]
The room agreed with what was said on Feb 29, closing this one out. This functionality can be part of either CDN/origin config or some other mechanism outside the CMCD spec.
