### ISSUE TITLE
Support multiple values in 'nor'

### ISSUE THREAD

**Issue by pankaj-giter** [cta-wave/common-media-client-data#83]
Use Case: Playback start for HLS and DASH can benefit from prefetching more than one object on the CDN edge server. 

Request: Support multiple values for the 'nor' key or a new key.

**Comment by PCaponetti** [comment]
David: could be a good value
Paul: should be easy to implement if you already support `nor` on the proxy end
David: potentially an issue for backward compatibility if we don't allow single or array. would that be an undue burden on the parser
Jim and Paul: haven't seen a ton of value in prefech
David: could have value in getting insight into sequencing of requests?
Jim: some people consider nor to be very verbose and drop it. would love for a way to make it more terse. have seen players send absolute URLs. need to check in on this on the validator.
Nicolas: validator checks that nor is relative
Jordan: requires a bit of an algorithm because it is relative to the request being made, not the manifest

Proposed some language in the spec under the nor key:

Multiple objects may be represented as specified in RFC [8941](https://www.rfc-editor.org/rfc/rfc8941.html#name-inner-lists).

**Comment by wilaw** [comment]
CMSD uses

nor="/video/1080/1080p-playlist.m3u8|/video/720/720p-playlist.m3u8|/video/480/480p-playlist.m3u8|/audio/audio-playlist.m3u8|/video/1080/init.mp4|/video/720/init.mp4|/video/480/init.mp4|/audio/init.mp4|/video/1080/seg1.mp4|/video/720/seg1.mp4|/video/480/seg1.mp4"

**Comment by PCaponetti** [comment]
Will and Chris: try and mirror CMSD, there is an issue with 8941 due to sublists not being valid, so in CMSD we used a pipe delimited string
Chris: 98% backwards compatible unless someone uses a pipe in the URI and a non-standard url encoder that doesn't encode pipes
Will: will have to also make `nrr` as well to apply a range to each element
Chris: what about pulling `nor` into a header to allow for sublist?
Will: adding a new header is too much work for parsers
Will: `nrr` has <suffix-length>, do we need that?
Chris: that language was stollen from the range request list, but what do we get from omitting it?


Updated the spec stealing words form CMSD for `nor` and `nrr`.
