### ISSUE TITLE
Custom keys must have a value type of STRING

### ISSUE THREAD

**Issue by wilaw** [cta-wave/common-media-client-data#86]
Currently custom keys are allowed, but the spec is ambivalent about the value type, which presumably could be any of number, string or token. This makes it difficult to build robust parsers. It would be better if only the STRING type was allowed and if we constrained it to some length such as 64 chars. 

Current:
com.example-data: h
com.example-data: 11131
com.example-data: -21
com.example-data: "abc"
com.example-data: "dlfghjadjlfsdjfhskdjhfueyrwiueyskjdhfksjrywerwerwerwewerwsddfsddnq,wehqwuyaosdyasyiquwyiuyasiduayisudyaisuynwyinquwyeinquwyisquwyesinquwyeiquwyociusceriuwoiucowieurcnownowiueocniweuroynow"

Proposed
com.example-data: "h"
com.example-data: "11131"
com.example-data: "-21"
com.example-data: "abc"
com.example-data: "dlfghjadjlfsdjfhskdjhfueyrwiueyskjdhfksjrywerwerwerwewerwsddfsdd"

**Comment by nicolaslevy** [comment]
Seems reasonable to me. The "owner" of the key will always know the type and can change it in any time with no advice.

**Comment by PCaponetti** [comment]
Will: In my experience anything unknown is coerced to a string anyway.
Rajeev: +1
Will: Should we enforce a limit? I don't think we should.
Chris L: Do we expect this to be parsed by people who don't understand it (middle proxies?)?
Will: Yes, and we should limit it in that case. Maybe 128?
Glenn: Not sure the size of single fields is an issue, but the whole set of CMCD signal. Should we have an overall limit?
Will: practically people don't abuse things, and we have put constraints on session ID
Glenn: You could also shard your 128 payload over 2 64 length fields
Jim: There is a limit for query string anyway based on URL length
Gwendal: CDNs need to export the CMCD data, and some of the fields are way too big and we need to filter. This is done today in some CDNs with `nor` and some other fields.
Rajeev: Maybe allow truncation for uninterested parties?
Will: We shouldn't define logging or similar mechanisms in the CMCD spec.
Chris L: Should we allow for byte strings too?
Piers: Colons instead of quotes on byte strings, and base 64
Will: Is the premise of this issue weak? Will parsers not have a problem parsing these values?
Chris L: Parsers may not have an issue but other data structures might like inserting into database with types.

Added language to section 3.2 to bake: "Custom keys MUST have a value type of STRING or TOKEN and a maximum character count of 64."

**Comment by wilaw** [comment]
Meeting 2/15
 - Paul reviewed language added and size constraint. Does 64 char limit hurt?
 - Will, can add UUID in that size, so OK. Plus, users can have as many keys as they want. 
 - Paul - this is least annoying size. A size of 128 char would be fine for our CDN. 
 - Will, 64 would be better to keep log size smaller. 
 - Accepted text.
