### ISSUE TITLE
Header examples show incorrect escaping of 'nor' values

### ISSUE THREAD

**Issue by wilaw** [cta-wave/common-media-client-data#88]
Section 3.2.10 of the spec says  "Data payloads transmitted via headers MUST NOT be URLEncoded".

Examples 6.1.6, 6.1.8 and 6.1.9 then show incorrect escaping of the '/' character within the nor values, as shown below:

`CMCD-Request:nor="..%2F300kbps%2Fsegment35.m4v"`
`CMCD-Request:nor="..%2F300kbps%2Ftrack.m4v"`

**Comment by alficles** [comment]
I believe the examples are correct. In section 3.3, the Next Object Request value definition says: "This string MUST be URLEncoded.

So, the string itself must be URL Encoded, but once so encoded, the resultant value MUSTN'T be encoded again. The examples in section 6.2 are illustrative. 6.2.6 starts "?CMCD=nor%3D%22..%252F". That "%252F" is what you get when you percent-encode "%2F" because the percent-encoding of the percent sign is "%25".

The value of a nor field is URLEncoded once because its definition says so. That result is URLEncoded a second time for Query transport but not for Header transport.

**Comment by PCaponetti** [comment]
Talked about this today, the room felt strongly that the URL encoding or not URL encoding should not be part of the definition of any particular field, but we should be (and currently are) clear about handling URL encoding properly with regard to how we are sending CMCD data.

Suggested to remove the bit about nor being URL encoded.

Chris L to suggest some language (or comment on language) for section 3.2 to better reinforce this point.

**Comment by alficles** [comment]
One important factor is is how people have implemented it. It would be better not to URI encode it when passed via header. However, I think backward compatibility is important on this one. We want to make sure we're not breaking existing implementations unnecessarily. Or at least, not without consideration.

**Comment by PCaponetti** [comment]
Will: worried about removing the url encoding for fields like nor
Chris L: this is one that is not worth breaking backward compatibility on. We do call this a structured field string value which already does have a quote escape, so we can remove url encoding if we want.
Will: It looks like URL encoding got taken out, we'll have to re-add it or ensure quotes or | is encoded/escaped
Chris L/Will: conversation on whether to force the client to encode a certain way or forward on the flexibility afforded us. Decided to be more prescriptive to allow for consistency and easy of understanding at the CDN side.

A lot of talk about how much or little encoding we should be forcing on the player and CDN. More encoding leads to unreadable and overly large payloads, less might lead to less streamlined producing or consuming of the field.

Paul C: do we get rid or multiple nor values? that would make this problem even less unique to us.

Started evaluating other proposed formats, then looked at incorporating encoding rules by reference instead of redefining them.

Changes to the doc:
- Switched `nor`'s type to be "A Inner List of strings", taking out all mention of encoding in the description.
- Added text to 4.1 to note where things should be encoded as JSON array (if value type is "Inner List") AND added a reference to the JSON spec.
- Still working on nrr (will continue with next comment)

**Comment by wilaw** [comment]
Chris: proposes a more efficient SFV form for NRR when being transmitted via JSON. Values that have parameters MUST be encoded as Object types. Chose the object name 
Paul: slightly confusing is better than no method


Group deleted the 'nrr' key and modified the definition of 'nor'

> The relative path to one or more objects which can reasonably be expected to be requested by the client making the current request. Each object SHOULD be fetched in its entirety unless there is a range associated with the future request.  If there is a range associated with the future request, then the range is communicated as the parameter 'r' with a String value. The formatting of the String value is similar to the HTTP Range header, except that the unit MUST be ‘byte’, the ‘Range:’ prefix is NOT permitted, specifying multiple ranges is NOT allowed and the only valid combinations are:
> "<range-start>-"
> "<range-start>-<range-end>"
> "-<suffix-length>
> The client SHOULD NOT depend upon any pre-fetch action being taken - it is merely a request for such a pre-fetch to take place. 
> 
> Per [4] Sect 3.1.1, an Inner List  is denoted by opening (Unicode 0x28) and closing (Unicode 0x29) parenthesis, with each internal element contained within double quotes (Unicode 0x22) and separated by a space (Unicode 0x20).
> 
>
