### ISSUE TITLE
Support absolute path and absolute URL for 'nor' key

### ISSUE THREAD

**Issue by pankaj-giter** [cta-wave/common-media-client-data#97]
v1 of CMCD's "nor" specifies the value as "relative path of the object to prefetch..." where this path is relative to the current object being requested. 
There are many use cases why the next object may not be easily defined relative to the current request:
1. switching bitrates
2. mix of bumper/ad/main content in a SSAI/DAI generated playlist where each of the bumper, Ad and main content are in 3 different directories or 3 different origins (hence potentially different hostnames)

If we were to support the above use cases via relative path, we will have to rely on the ".." notation, such as, "../../../bumper/en-us/hulu/1080p/seg1.mp4".
The 'dot' notation is doable but cumbersome to use and hence error prone. It is much simpler to support absolute paths and URLs.

**Comment by wilaw** [comment]
+1 to allowing absolute URLS in 'nor' to improve ad boundary transitions. 

One concern is that the prefetching benefit can only be realized if the CDN serving the primary content is the same CDN that is used to deliver the ad content.

**Comment by wilaw** [comment]
Alex - if CDN is not required, then OK. 
Will - with CNAME its difficult to tell if you are the same CDN. 
Nico - in v1 bad player will still send absolute  path. CDN should protect itself. 
Will - in v1, CDN will immediately reject an absolute path. More work to validate absolute paths.
Gwendal - I have seen absolute paths in v1 already, prefer not having it.

**Comment by PCaponetti** [comment]
Chris L: Thought about this in v1 and left it out because it could lead to reflect and create a DoS from a CDN.
Nicolas: there are already v1 implementations that send the full path (as noted by Gwendal), thinking we'll have to rely on the CDN to protect itself and origins.
Chris L/Will: we allow full paths in CMSD because we trust the origin more.
Chris L: The use case is real, though, to improve ad boundaries. Maybe we add an allowlist at the CDN and allow absolute URL in `nor`.
Alex G: +1 for allowlist at the CDN and keeping us open to the unsafe possible DoS
Will: Simplest is to keep it as-is and require relative paths only, and it is the safest as well. Also many times the ad is handled by a different player or has different special handling anyway.

won't allow this for v2
