### ISSUE TITLE
Clarify 'nor' and 'ot' field values

### ISSUE THREAD

**Issue by rohitjoins** [cta-wave/common-media-client-data#99]
I need to clarify about two fields in CMCD spec:

1. `ot`: The definition includes the object types `c` for caption or subtitle and `tt` for ISOBMFF timed text track. Does this imply that if the text is in WebVTT/TTML format muxed inside MP4 container, it should be referred to as `tt`, whereas if it is simply a standalone text file, it should be called `c`?
2. `nor`: Is it expected that the player will always send a wrong value for `nor` before an adaptive switch? As there is no way to know if an adaptive switch will happen before it actually does.

**Comment by wilaw** [comment]
Hi Rohit

1. Yes, 'c' for text files and 'tt' for ISOBMFF encapsulated timed text data. If you feel that this is not a useful categorization and that instead we should signal all caption content irrespective of its encapsulation to be'c', then please file a separate issue for this to be addressed in v2. 
2. A standard player will likely send the incorrect value for 'nor' right before a switch. A downswitch can never be predicted or delayed, therefore this will always be the case for down-switches. An upswitch however may be delayed by one segment duration intentionally by a smart player, in order to signal the correct value for 'nor' and thus avoid a cold hit on the upswitch. Whether to do this or not will depend on the relative benefit of avoiding the cold hit versus staying on the lower quality for one segment longer.

**Comment by rohitjoins** [comment]
Hi Will,

Thanks for a prompt reply. It helps clarify the doubts I had. Closing this issue as resolved.
